# Generated by Django 3.2.2 on 2021-05-15 15:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название города')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(verbose_name='Текст сообщения')),
                ('message_image', models.ImageField(blank=True, upload_to='images/messages/', verbose_name='Изображение')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.city')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ('date',),
            },
        ),
    ]
